-- The retired starter-catalogue seed included invented stock, minimum orders,
-- and third-party image URLs. Keep those known rows editable but unpublished
-- and remove every sellable value until staff enter client-approved data.
UPDATE "catalog_listings"
SET "price" = NULL,
    "compareAtPrice" = NULL,
    "priceNote" = NULL,
    "offerLabel" = NULL,
    "offerStartsAt" = NULL,
    "offerEndsAt" = NULL,
    "isInStock" = FALSE,
    "availabilityStatus" = 'CHECK_AVAILABILITY',
    "minOrderQty" = NULL,
    "image" = NULL,
    "galleryImages" = '{}',
    "isPublished" = FALSE,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "slug" IN (
  'asian-paints-royale-play',
  'asian-paints-royale-glitz',
  'asian-paints-royale',
  'asian-paints-ace-exterior-emulsion',
  'asian-paints-apex-ultima-suprema-air-o-clean',
  'asian-paints-smartcare-damp-proof',
  'asian-paints-smartcare-damp-block-2k',
  'asian-paints-smartcare-infinia',
  'asian-paints-smartcare-hydroloc',
  'asian-paints-woodtech-pu-palette',
  'asian-paints-woodtech-aquadur-pu-interior-matt',
  'asian-paints-woodtech-melamyne',
  'berger-silk-glamor-dazzle',
  'berger-silk-glamor-high-sheen',
  'berger-silk-glamor-soft-sheen',
  'berger-silk-glamor-matt',
  'berger-silk-metallics',
  'berger-silk-glamart-metallica',
  'berger-silk-glamart-metallica-for-designs',
  'berger-silk-glamart-non-metallic',
  'berger-silk-glamart-vintage',
  'berger-silk-glamart-stucco',
  'berger-silk-glamart-stones-tones',
  'berger-easy-clean',
  'ultratech-grey-cement-ordinary-portland-cement',
  'ultratech-grey-cement-portland-pozzolana-cement',
  'ultratech-grey-cement-portland-pozzolana-super',
  'ultratech-grey-cement-composite-cement',
  'ultratech-grey-cement-weather-plus',
  'ultratech-grey-cement-portland-slag-cement',
  'ultratech-birla-white-cement',
  'ultratech-birla-white-wall-care-putty',
  'ultratech-weather-pro-waterproofing-system',
  'ultratech-tilefixo-sumo-ct',
  'ultratech-tilefixo-nt',
  'ultratech-tilefixo-yt',
  'ultratech-readiplast',
  'ultratech-super-stucco',
  'astral-pex-a-pro',
  'astral-multipex',
  'astral-aquarius',
  'astral-eco-pro',
  'astral-chem-flow',
  'astral-silencio',
  'astral-drain-pro',
  'polycab-green-wire',
  'polycab-suprema-with-e-beam-technology',
  'polycab-optima',
  'polycab-primma',
  'polycab-hr-fr-lsh-lf-green-wire',
  'ultratech-super',
  'ambuja-kawach',
  'jk-super-cement',
  'shree-cement-roofon',
  'astral-cpvc-pro',
  'supreme-swr-pipes',
  'finolex-upvc-pipes',
  'zoloto-brass-valves',
  'polycab-fr-wires',
  'havells-lifeline-plus',
  'finolex-flame-retardant',
  'tata-tiscon-550d',
  'asian-paints-apex-ultima',
  'birla-opus-paints',
  'jk-wallmaxx-putty',
  'jaquar-florentine-diverter',
  'cera-rimless-ewc',
  'myk-laticrete-adhesive',
  'asian-paints-tractor-emulsion',
  'polycab-etira-fr-wire',
  'supreme-cpvc-quote-sample',
  'supreme-agricultural-solvent-sample'
);

UPDATE "catalog_listing_variants"
SET "price" = NULL,
    "compareAtPrice" = NULL,
    "priceNote" = NULL,
    "offerLabel" = NULL,
    "offerStartsAt" = NULL,
    "offerEndsAt" = NULL,
    "isInStock" = FALSE,
    "availabilityStatus" = 'CHECK_AVAILABILITY',
    "stockQuantity" = NULL,
    "minOrderQuantity" = NULL,
    "quantityBreaks" = '[]'::jsonb,
    "image" = NULL,
    "galleryImages" = '{}',
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "listingId" IN (
  SELECT "id"
  FROM "catalog_listings"
  WHERE "slug" IN (
    'asian-paints-royale-play',
    'asian-paints-royale-glitz',
    'asian-paints-royale',
    'asian-paints-ace-exterior-emulsion',
    'asian-paints-apex-ultima-suprema-air-o-clean',
    'asian-paints-smartcare-damp-proof',
    'asian-paints-smartcare-damp-block-2k',
    'asian-paints-smartcare-infinia',
    'asian-paints-smartcare-hydroloc',
    'asian-paints-woodtech-pu-palette',
    'asian-paints-woodtech-aquadur-pu-interior-matt',
    'asian-paints-woodtech-melamyne',
    'berger-silk-glamor-dazzle',
    'berger-silk-glamor-high-sheen',
    'berger-silk-glamor-soft-sheen',
    'berger-silk-glamor-matt',
    'berger-silk-metallics',
    'berger-silk-glamart-metallica',
    'berger-silk-glamart-metallica-for-designs',
    'berger-silk-glamart-non-metallic',
    'berger-silk-glamart-vintage',
    'berger-silk-glamart-stucco',
    'berger-silk-glamart-stones-tones',
    'berger-easy-clean',
    'ultratech-grey-cement-ordinary-portland-cement',
    'ultratech-grey-cement-portland-pozzolana-cement',
    'ultratech-grey-cement-portland-pozzolana-super',
    'ultratech-grey-cement-composite-cement',
    'ultratech-grey-cement-weather-plus',
    'ultratech-grey-cement-portland-slag-cement',
    'ultratech-birla-white-cement',
    'ultratech-birla-white-wall-care-putty',
    'ultratech-weather-pro-waterproofing-system',
    'ultratech-tilefixo-sumo-ct',
    'ultratech-tilefixo-nt',
    'ultratech-tilefixo-yt',
    'ultratech-readiplast',
    'ultratech-super-stucco',
    'astral-pex-a-pro',
    'astral-multipex',
    'astral-aquarius',
    'astral-eco-pro',
    'astral-chem-flow',
    'astral-silencio',
    'astral-drain-pro',
    'polycab-green-wire',
    'polycab-suprema-with-e-beam-technology',
    'polycab-optima',
    'polycab-primma',
    'polycab-hr-fr-lsh-lf-green-wire',
    'ultratech-super',
    'ambuja-kawach',
    'jk-super-cement',
    'shree-cement-roofon',
    'astral-cpvc-pro',
    'supreme-swr-pipes',
    'finolex-upvc-pipes',
    'zoloto-brass-valves',
    'polycab-fr-wires',
    'havells-lifeline-plus',
    'finolex-flame-retardant',
    'tata-tiscon-550d',
    'asian-paints-apex-ultima',
    'birla-opus-paints',
    'jk-wallmaxx-putty',
    'jaquar-florentine-diverter',
    'cera-rimless-ewc',
    'myk-laticrete-adhesive',
    'asian-paints-tractor-emulsion',
    'polycab-etira-fr-wire',
    'supreme-cpvc-quote-sample',
    'supreme-agricultural-solvent-sample'
  )
);
