-- Published, explicitly labelled online-reference examples for preview/testing.
-- These are not Material Square inventory or client-approved sell prices.
-- Availability is always CHECK_AVAILABILITY and all public prices carry a caveat.
INSERT INTO "catalog_listings" (
  "id", "slug", "code", "name", "brand", "brandTagline", "category",
  "categoryLabel", "unit", "packaging", "grade", "description", "priceNote",
  "isInStock", "availabilityStatus", "isPublished", "features", "applications",
  "specifications", "sortOrder", "updatedAt"
) VALUES
('ref-ultratech-ppc', 'ultratech-ppc-cement-50kg-reference', 'REF-ULTRATECH-PPC-50', 'UltraTech PPC Cement, 50 kg', 'UltraTech Cement', 'The Engineer''s Choice', 'cement', 'Cement & Aggregates', 'bag', '50 kg bag', 'PPC', 'Online reference example for product discovery. Confirm the exact grade, current client price, tax basis, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Portland Pozzolana Cement (PPC)', '50 kg bag'], ARRAY['Masonry', 'Plastering', 'General construction'], '{"Grade":"PPC","Pack size":"50 kg","Reference price source":"https://www.home-run.co/products/ultratech-ppc-cement","Reference source updated":"8 May 2026","Reference note":"Bangalore seller listing; local price and taxes may differ."}', 0, CURRENT_TIMESTAMP),
('ref-ambuja-ppc', 'ambuja-ppc-cement-50kg-reference', 'REF-AMBUJA-PPC-50', 'Ambuja PPC Cement, 50 kg', 'Ambuja Cement', 'Giant Compressive Strength', 'cement', 'Cement & Aggregates', 'bag', '50 kg bag', 'PPC', 'Online reference example for product discovery. Confirm the exact grade, current client price, tax basis, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Portland Pozzolana Cement (PPC)', '50 kg bag'], ARRAY['Masonry', 'Plastering', 'General construction'], '{"Grade":"PPC","Pack size":"50 kg","Reference price source":"https://www.tradeindia.com/products/50kg-ambuja-ppc-cement-c12901061.html","Reference source updated":"2026 listing","Reference note":"Seller listing; local price and taxes may differ."}', 1, CURRENT_TIMESTAMP),
('ref-jk-cement', 'jk-cement-50kg-reference', 'REF-JK-CEMENT-50', 'JK Cement, 50 kg bags', 'JK Cement', 'Build Safe & Strong', 'cement', 'Cement & Aggregates', 'bag', '50 kg bag', null, 'Online reference example with multiple cement types. Select a grade to see its listed reference price. Confirm the exact grade, current client price, tax basis, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Grade-specific selectable options', '50 kg bags'], ARRAY['Masonry', 'Plastering', 'General construction'], '{"Reference price source":"https://rdak.store/jk-cement-delhi/","Reference source updated":"July 2026","Reference note":"Delhi seller list; prices vary by quantity and delivery."}', 2, CURRENT_TIMESTAMP),
('ref-shree-cement', 'shree-cement-50kg-reference', 'REF-SHREE-CEMENT-50', 'Shree Cement, 50 kg bag', 'Shree Cement', 'Master Concrete Solution', 'cement', 'Cement & Aggregates', 'bag', '50 kg bag', null, 'Online reference example for product discovery. A current product-specific local price was not available in the checked sources; request a quotation and confirm grade, stock and delivery.', 'Reference listing • request current price and confirm availability', false, 'CHECK_AVAILABILITY', true, ARRAY['50 kg bag'], ARRAY['General construction'], '{"Pack size":"50 kg","Reference price source":"https://www.shreecement.com/","Reference note":"No product-specific online price used; request a local quote."}', 3, CURRENT_TIMESTAMP),
('ref-astral-cpvc', 'astral-cpvc-pro-pipe-reference', 'REF-ASTRAL-CPVC-50', 'Astral CPVC Pro Pipe, 50 mm, 3 m', 'Astral Pipes', 'CPVC Pro & Lead Free', 'pipes', 'Pipes & Fittings', 'length', '3 m length', 'Class 2, SDR-13.5', 'Online reference example for a specific CPVC pipe size and length. Confirm pressure class, current client price, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['CPVC pipe for hot and cold water plumbing'], ARRAY['Hot and cold water plumbing'], '{"Diameter":"50 mm","Length":"3 m","Class":"Class 2","SDR":"13.5","Reference price source":"https://www.moglix.com/brands/astral/pipes/cpvc-pipes/119240100","Reference note":"Listed price ₹1,143; seller and delivery area affect final price."}', 4, CURRENT_TIMESTAMP),
('ref-supreme-cpvc', 'supreme-cpvc-lifeline-sdr135-reference', 'REF-SUPREME-CPVC-SDR135', 'Supreme CPVC LifeLine Pipe, SDR 13.5', 'Supreme Industries', 'People who know plastics best', 'pipes', 'Pipes & Fittings', 'meter', 'Sold by the metre', 'SDR 13.5', 'Online reference example with selectable diameters. Listed prices are per metre from a published price list; confirm current price, tax basis, stock, required length and delivery before ordering.', 'Online reference • list dated 21 May 2026 • confirm price & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['CPVC plumbing pipe', 'Diameter selectable'], ARRAY['Hot and cold water plumbing'], '{"Material":"CPVC","SDR":"13.5","Reference price source":"https://www.scribd.com/document/1074950151/SUPREME-CPVC-LIST-21-5-26","Reference note":"Published list price per metre; confirm current dealer quote and taxes."}', 5, CURRENT_TIMESTAMP),
('ref-finolex-pipes', 'finolex-cpvc-sdr11-pipe-reference', 'REF-FINOLEX-CPVC-20', 'Finolex CPVC SDR 11 Pipe, 20 mm, 3 m', 'Finolex Pipes', 'Pipes & Fittings', 'pipes', 'Pipes & Fittings', 'length', '3 m length', 'SDR 11', 'Online reference example for a specific pipe size and length. Request current pricing and confirm pressure class, stock and delivery before ordering.', 'Reference listing • request current price and confirm availability', false, 'CHECK_AVAILABILITY', true, ARRAY['CPVC pipe for hot and cold water plumbing'], ARRAY['Hot and cold water plumbing'], '{"Diameter":"20 mm","Length":"3 m","SDR":"11","Reference price source":"https://lntsufin.com/product/finolex-20-mm-cpvc-pipes-2-5-mm-sdr-11-3-m/16248-2172","Reference note":"Seller price is quote-based; no fixed online price copied."}', 6, CURRENT_TIMESTAMP),
('ref-zoloto-valve', 'zoloto-forged-brass-ball-valve-reference', 'REF-ZOLOTO-BALL-VALVE', 'Zoloto Forged Brass Ball Valve', 'Zoloto Valves', 'Forged Brass & Bronze Valves', 'pipes', 'Pipes & Fittings', 'piece', 'One valve', null, 'Online reference example with selectable nominal bore sizes. Confirm valve material, pressure rating, current client price, stock and delivery before ordering.', 'Online reference • list dated 26 May 2026 • confirm price & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Forged brass ball valve', 'Nominal bore selectable'], ARRAY['Water line isolation'], '{"Material":"Forged brass","Reference price source":"https://www.vijaysalescorp.com/zoloto-valves-price-list","Reference note":"Dealer price list effective 26 May 2026."}', 7, CURRENT_TIMESTAMP),
('ref-polycab-wire', 'polycab-suprema-wire-25-red-90m-reference', 'REF-POLYCAB-SUPREMA-25-RED', 'Polycab Suprema HR-FR-LSH-LF Copper Wire, 2.5 sq mm, Red, 90 m', 'Polycab Wires', 'Wires & Cables', 'wires', 'Wires & Cables', 'coil', '90 m coil', '2.5 sq mm, single core', 'Online reference example for a specific wire size, colour and coil length. Confirm conductor type, current client price, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Copper conductor', 'HR-FR-LSH-LF insulation'], ARRAY['Residential and commercial wiring'], '{"Conductor":"Copper","Cross section":"2.5 sq mm","Core":"Single core","Colour":"Red","Length":"90 m","Reference price source":"https://polycab.com/polycabsuprema-25-sq-mm-90-meters-red/c-56841/p-56981","Reference note":"Manufacturer page MRP ₹9,650 including tax; confirm local selling price."}', 8, CURRENT_TIMESTAMP),
('ref-havells-wire', 'havells-life-guard-wire-25-black-reference', 'REF-HAVELLS-LIFEGUARD-25-BLK', 'Havells Life Guard FR-LSH House Wire, 2.5 sq mm, Black, 90 m', 'Havells India', 'Wires That Never Catch Fire', 'wires', 'Wires & Cables', 'coil', '90 m coil', '2.5 sq mm, single core', 'Online reference example for a specific wire size, colour and coil length. Confirm conductor type, current client price, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['FR-LSH house wire'], ARRAY['Residential and commercial wiring'], '{"Conductor":"Copper","Cross section":"2.5 sq mm","Core":"Single core","Colour":"Black","Length":"90 m","Reference price source":"https://elumenuvo.com/catalogue/wire-havells-frlsh-2p5-black","Reference note":"Dealer reference ₹4,491; displayed MRP ₹5,299. Verify the live offer."}', 9, CURRENT_TIMESTAMP),
('ref-finolex-wire', 'finolex-fr-wire-25-reference', 'REF-FINOLEX-FR-WIRE-25', 'Finolex FR House Wire, 2.5 sq mm, 90 m', 'Finolex Cables Limited', 'Cables Limited', 'wires', 'Wires & Cables', 'coil', '90 m coil', '2.5 sq mm, single core', 'Online reference example for product discovery. Request current pricing and confirm colour, conductor, stock and delivery before ordering.', 'Reference listing • request current price and confirm availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Flame retardant house wire'], ARRAY['Residential and commercial wiring'], '{"Cross section":"2.5 sq mm","Core":"Single core","Length":"90 m","Reference product source":"https://www.cauverypowers.com/products/finolex-25-sqmm-fr-wire-90mtr-green-SKU-3206","Reference note":"Current seller price not published in the checked listing."}', 10, CURRENT_TIMESTAMP),
('ref-asian-paints', 'asian-paints-apcolite-all-protek-matt-reference', 'REF-ASIAN-APCOLITE-ALL-PROTEK-MATT', 'Asian Paints Apcolite All Protek Matt Interior Paint', 'Asian Paints', 'Har Ghar Kuch Kehta Hai', 'paints', 'Paints & Waterproofing', 'tin', 'Interior wall paint', 'Matt finish', 'Online reference example with selectable pack sizes. Colour tinting and shade charges can change the final price; confirm the shade, client price, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm shade, price & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Interior wall paint', 'Matt finish', 'Shade tinting may affect price'], ARRAY['Interior walls'], '{"Finish":"Matt","Base shade":"White base; ask about tinted shades","Reference price source":"https://www.asianpaints.com/content/ap/en/home/products/paints-and-textures/interior-walls/plain-finishes/apcolite-all-protek-Matte.html","Reference note":"Manufacturer pack prices; shade, pack, location and availability affect final quote."}', 11, CURRENT_TIMESTAMP),
('ref-birla-opus', 'birla-opus-one-pure-elegance-20l-reference', 'REF-BIRLA-OPUS-ONE-PURE-20', 'Birla Opus One Pure Elegance Interior Paint, 20 L', 'Birla Opus Paints', 'Rich Colours, Superior Finish', 'paints', 'Paints & Waterproofing', 'tin', '20 L bucket', 'Premium interior emulsion', 'Online reference example for a premium interior paint family and pack size. Confirm base shade, tinting, current client price, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm shade, price & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Interior emulsion', 'Available in multiple pack sizes and shades'], ARRAY['Interior walls'], '{"Finish":"Interior paint","Pack size":"20 L","Base shade":"Select base and shade with staff","Reference price source":"https://aapkapainter.com/products/paints/birla-opus-price","Reference note":"2026 reference table shows ₹14,240 for 20 L; confirm current MRP and dealer quote."}', 12, CURRENT_TIMESTAMP),
('ref-jaquar-basin-tap', 'jaquar-basin-tap-reference', 'REF-JAQUAR-BASIN-TAP', 'Jaquar Basin Tap, Chrome Finish (Reference Example)', 'Jaquar Bath + Light', 'Bath + Light', 'sanitary', 'Sanitaryware & Bath Fittings', 'piece', 'One tap', null, 'Online reference example for a chrome basin tap. The cited price is a published starting price across a range, not a confirmed price for every model; confirm the model code, finish, current price and stock.', 'Online reference • 2026 range starting price • confirm model & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Chrome finish example'], ARRAY['Bathroom basin'], '{"Finish":"Chrome example","Reference price source":"https://www.padmavaticeramics.com/guides/jaquar-taps-price-list-2026","Reference note":"2026 dealer guide lists basin taps starting at ₹1,610; model-specific prices vary."}', 13, CURRENT_TIMESTAMP),
('ref-cera-mixer', 'cera-chromo-wall-basin-mixer-reference', 'REF-CERA-CHROMO-F1019473', 'CERA Chromo Wall-Mounted Basin Mixer, F1019473, Chrome', 'CERA Sanitaryware', 'Sanitaryware | Faucets | Tiles', 'sanitary', 'Sanitaryware & Bath Fittings', 'piece', 'One mixer', null, 'Online reference example for a specific mixer model and finish. Confirm mounting type, included fittings, current client price, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Wall-mounted basin mixer', 'Chrome finish'], ARRAY['Bathroom basin'], '{"Model":"F1019473","Finish":"Chrome","Reference price source":"https://www.padmavaticeramics.com/collections/cera-wall-mounted-basin-mixers","Reference note":"Dealer listing ₹2,880; MRP ₹3,200. Verify live price and availability."}', 14, CURRENT_TIMESTAMP),
('ref-tata-tiscon', 'tata-tiscon-550sd-tmt-12mm-reference', 'REF-TATA-TISCON-550SD-12', 'Tata Tiscon 550SD TMT Rebar, 12 mm, 12 m', 'Tata Tiscon', 'Desh Ka Saria', 'steel', 'Steel & TMT Bars', 'piece', '12 m bar', 'Fe 550SD', 'Online reference example for a standard rebar size and grade. Steel pricing depends on location and date; request a current quote and confirm weight, tax, stock and delivery.', 'Reference listing • location-based steel price; request current quote', false, 'CHECK_AVAILABILITY', true, ARRAY['Fe 550SD grade', '12 m standard bar length'], ARRAY['Reinforced concrete construction'], '{"Diameter":"12 mm","Grade":"Fe 550SD","Length":"12 m","Reference product source":"https://tatatiscon.co.in/wp-content/uploads/2026/05/TISCON-550SD-Brochures-8x12-Eng-FINAL.pdf","Reference price source":"https://civilsite.in/tata-tiscon-price-list-today/","Reference note":"Tata price is location-specific; use the official RCP checker on quote day."}', 15, CURRENT_TIMESTAMP),
('ref-myk-315', 'myk-laticrete-315-plus-tile-adhesive-reference', 'REF-MYK-315-PLUS-20', 'MYK Laticrete 315 Plus Premium Tile Adhesive, 20 kg', 'MYK Laticrete', 'World Leader in Tile Adhesives', 'adhesives', 'Adhesives & Grouts', 'bag', '20 kg bag', '315 Plus', 'Online reference example with selectable bag colours. Confirm substrate suitability, current client price, stock and delivery before ordering.', 'Online reference • observed 06 Oct 2026 • confirm price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Polymer-modified thin-set adhesive', 'Floor and wall applications'], ARRAY['Ceramic and vitrified tile installation'], '{"Pack size":"20 kg","Reference price source":"https://home-run.co/pages/price-list/myk-laticrete","Reference note":"Bangalore seller list dated 8 May 2026; bulk tiers, location and taxes may vary."}', 16, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;

-- Variant-level reference prices preserve pack, colour, diameter and grade choices.
-- Each option remains availability-check-only; client inventory is not implied.
WITH variant_seed("listingSlug", "code", "label", "attributes", "unit", "price", "compareAtPrice", "priceNote", "sortOrder") AS (
  VALUES
  ('ultratech-ppc-cement-50kg-reference','REF-ULTRA-PPC-50','PPC · 50 kg','{"Grade":"PPC","Pack":"50 kg"}'::jsonb,'bag',425.00::numeric,NULL::numeric,'HomeRun Bangalore reference; confirm local price.',0),
  ('ambuja-ppc-cement-50kg-reference','REF-AMBUJA-PPC-50','PPC · 50 kg','{"Grade":"PPC","Pack":"50 kg"}'::jsonb,'bag',370.00::numeric,NULL::numeric,'TradeIndia seller reference; confirm local price.',0),
  ('jk-cement-50kg-reference','REF-JK-SUPER-PPC','Super PPC · 50 kg','{"Type":"Super PPC","Pack":"50 kg"}'::jsonb,'bag',308.00::numeric,NULL::numeric,'Delhi seller reference; confirm local price.',0),
  ('jk-cement-50kg-reference','REF-JK-SUPER-STRONG','Super Strong · 50 kg','{"Type":"Super Strong","Pack":"50 kg"}'::jsonb,'bag',330.00::numeric,NULL::numeric,'Delhi seller reference; confirm local price.',1),
  ('jk-cement-50kg-reference','REF-JK-OPC43','Super OPC 43 · 50 kg','{"Type":"Super OPC 43","Pack":"50 kg"}'::jsonb,'bag',340.00::numeric,NULL::numeric,'Delhi seller reference; confirm local price.',2),
  ('jk-cement-50kg-reference','REF-JK-SUPER-PROTECT','Super Protect · 50 kg','{"Type":"Super Protect","Pack":"50 kg"}'::jsonb,'bag',355.00::numeric,NULL::numeric,'Delhi seller reference; confirm local price.',3),
  ('shree-cement-50kg-reference','REF-SHREE-50','50 kg · select cement grade','{"Pack":"50 kg","Grade":"Confirm with staff"}'::jsonb,'bag',NULL::numeric,NULL::numeric,'Request a current product and location-specific quote.',0),
  ('astral-cpvc-pro-pipe-reference','REF-ASTRAL-50MM-3M','50 mm · 3 m · SDR 13.5','{"Diameter":"50 mm","Length":"3 m","SDR":"13.5"}'::jsonb,'length',1143.00::numeric,NULL::numeric,'Moglix listing reference; confirm current quote.',0),
  ('supreme-cpvc-lifeline-sdr135-reference','REF-SUPREME-15-SDR135','15 mm','{"Diameter":"15 mm","SDR":"13.5"}'::jsonb,'meter',104.80::numeric,NULL::numeric,'Published list price per metre; confirm taxes and dealer price.',0),
  ('supreme-cpvc-lifeline-sdr135-reference','REF-SUPREME-20-SDR135','20 mm','{"Diameter":"20 mm","SDR":"13.5"}'::jsonb,'meter',159.40::numeric,NULL::numeric,'Published list price per metre; confirm taxes and dealer price.',1),
  ('supreme-cpvc-lifeline-sdr135-reference','REF-SUPREME-25-SDR135','25 mm','{"Diameter":"25 mm","SDR":"13.5"}'::jsonb,'meter',220.60::numeric,NULL::numeric,'Published list price per metre; confirm taxes and dealer price.',2),
  ('supreme-cpvc-lifeline-sdr135-reference','REF-SUPREME-32-SDR135','32 mm','{"Diameter":"32 mm","SDR":"13.5"}'::jsonb,'meter',323.80::numeric,NULL::numeric,'Published list price per metre; confirm taxes and dealer price.',3),
  ('supreme-cpvc-lifeline-sdr135-reference','REF-SUPREME-40-SDR135','40 mm','{"Diameter":"40 mm","SDR":"13.5"}'::jsonb,'meter',475.30::numeric,NULL::numeric,'Published list price per metre; confirm taxes and dealer price.',4),
  ('supreme-cpvc-lifeline-sdr135-reference','REF-SUPREME-50-SDR135','50 mm','{"Diameter":"50 mm","SDR":"13.5"}'::jsonb,'meter',779.20::numeric,NULL::numeric,'Published list price per metre; confirm taxes and dealer price.',5),
  ('finolex-cpvc-sdr11-pipe-reference','REF-FINOLEX-20-SDR11','20 mm · 3 m · SDR 11','{"Diameter":"20 mm","Length":"3 m","SDR":"11"}'::jsonb,'length',NULL::numeric,NULL::numeric,'Request current quote; listing is RFQ-based.',0),
  ('zoloto-forged-brass-ball-valve-reference','REF-ZOLOTO-15NB','15 NB','{"Nominal bore":"15 NB"}'::jsonb,'piece',640.00::numeric,NULL::numeric,'Zoloto dealer list reference; confirm current quote.',0),
  ('zoloto-forged-brass-ball-valve-reference','REF-ZOLOTO-20NB','20 NB','{"Nominal bore":"20 NB"}'::jsonb,'piece',886.00::numeric,NULL::numeric,'Zoloto dealer list reference; confirm current quote.',1),
  ('zoloto-forged-brass-ball-valve-reference','REF-ZOLOTO-25NB','25 NB','{"Nominal bore":"25 NB"}'::jsonb,'piece',1402.00::numeric,NULL::numeric,'Zoloto dealer list reference; confirm current quote.',2),
  ('polycab-suprema-wire-25-red-90m-reference','REF-POLYCAB-25-RED-90','Red · 2.5 sq mm · 90 m','{"Colour":"Red","Cross section":"2.5 sq mm","Length":"90 m"}'::jsonb,'coil',9650.00::numeric,NULL::numeric,'Manufacturer MRP reference including tax; confirm local selling price.',0),
  ('havells-life-guard-wire-25-black-reference','REF-HAVELLS-25-BLACK-90','Black · 2.5 sq mm · 90 m','{"Colour":"Black","Cross section":"2.5 sq mm","Length":"90 m"}'::jsonb,'coil',4491.00::numeric,5299.00::numeric,'Dealer offer reference; confirm live price and stock.',0),
  ('finolex-fr-wire-25-reference','REF-FINOLEX-25-90','2.5 sq mm · 90 m','{"Cross section":"2.5 sq mm","Length":"90 m"}'::jsonb,'coil',NULL::numeric,NULL::numeric,'Request current price for colour and coil.',0),
  ('asian-paints-apcolite-all-protek-matt-reference','REF-ASIAN-AP-1L','1 L · white base','{"Pack":"1 L","Colour":"White base"}'::jsonb,'tin',556.00::numeric,NULL::numeric,'Manufacturer pack-price reference; shade tinting can change price.',0),
  ('asian-paints-apcolite-all-protek-matt-reference','REF-ASIAN-AP-4L','4 L · white base','{"Pack":"4 L","Colour":"White base"}'::jsonb,'tin',2196.00::numeric,NULL::numeric,'Manufacturer pack-price reference; shade tinting can change price.',1),
  ('asian-paints-apcolite-all-protek-matt-reference','REF-ASIAN-AP-10L','10 L · white base','{"Pack":"10 L","Colour":"White base"}'::jsonb,'tin',5270.00::numeric,NULL::numeric,'Manufacturer pack-price reference; shade tinting can change price.',2),
  ('asian-paints-apcolite-all-protek-matt-reference','REF-ASIAN-AP-20L','20 L · white base','{"Pack":"20 L","Colour":"White base"}'::jsonb,'tin',10117.00::numeric,NULL::numeric,'Manufacturer pack-price reference; shade tinting can change price.',3),
  ('birla-opus-one-pure-elegance-20l-reference','REF-BIRLA-ONE-PURE-20L','20 L · confirm shade base','{"Pack":"20 L","Colour":"Confirm base/shade"}'::jsonb,'bucket',14240.00::numeric,NULL::numeric,'2026 paint-dealer list reference; confirm colour and current rate.',0),
  ('jaquar-basin-tap-reference','REF-JAQUAR-BASIN-CHROME','Chrome · basin tap starting-price example','{"Finish":"Chrome","Type":"Basin tap"}'::jsonb,'piece',1610.00::numeric,NULL::numeric,'Published 2026 range starting price; not tied to every model.',0),
  ('cera-chromo-wall-basin-mixer-reference','REF-CERA-F1019473-CHROME','Chrome · wall mounted · F1019473','{"Finish":"Chrome","Mount":"Wall mounted","Model":"F1019473"}'::jsonb,'piece',2880.00::numeric,3200.00::numeric,'Authorized-dealer listing reference; confirm live offer.',0),
  ('tata-tiscon-550sd-tmt-12mm-reference','REF-TATA-550SD-12MM','12 mm · Fe 550SD · 12 m','{"Diameter":"12 mm","Grade":"Fe 550SD","Length":"12 m"}'::jsonb,'piece',NULL::numeric,NULL::numeric,'Request location-specific Tiscon RCP and current dealer quote.',0),
  ('myk-laticrete-315-plus-tile-adhesive-reference','REF-MYK-315-GREY-20','Grey · 20 kg','{"Colour":"Grey","Pack":"20 kg"}'::jsonb,'bag',625.00::numeric,NULL::numeric,'HomeRun Bangalore seller reference; confirm local price and taxes.',0),
  ('myk-laticrete-315-plus-tile-adhesive-reference','REF-MYK-315-WHITE-20','White · 20 kg','{"Colour":"White","Pack":"20 kg"}'::jsonb,'bag',775.00::numeric,NULL::numeric,'HomeRun Bangalore seller reference; confirm local price and taxes.',1)
)
INSERT INTO "catalog_listing_variants" (
  "id", "listingId", "code", "label", "attributes", "unit", "price",
  "compareAtPrice", "priceNote", "isInStock", "availabilityStatus", "sortOrder", "updatedAt"
)
SELECT
  'refv-' || lower(regexp_replace(v."code", '[^a-zA-Z0-9]+', '-', 'g')),
  l."id", v."code", v."label", v."attributes", v."unit", v."price",
  v."compareAtPrice", v."priceNote", false, 'CHECK_AVAILABILITY', v."sortOrder", CURRENT_TIMESTAMP
FROM variant_seed v
JOIN "catalog_listings" l ON l."slug" = v."listingSlug"
ON CONFLICT ("code") DO NOTHING;
