-- Keep the former preview listings in the protected admin catalogue, but do
-- not expose them to customers until the client reviews and publishes them.
UPDATE "catalog_listings"
SET "isPublished" = FALSE,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "slug" IN (
  -- Names generated by seed-starter-catalog.cjs. Unpublish by stable slug so
  -- edits made to a draft cannot accidentally make starter data public.
  'asian-paints-royale-play',
  'asian-paints-royale-glitz',
  'asian-paints-royale',
  'asian-paints-ace-exterior-emulsion',
  'asian-paints-apex-ultima-suprema-air-o-clean',
  'asian-paints-smartcare-damp-proof',
  'asian-paints-smartcare-damp-block-2k',
  'asian-paints-smartcare-infinia',
  'asian-paints-smartcare-hydroloc',
  'asian-paints-woodtech-pu-palette',
  'asian-paints-woodtech-aquadur-pu-interior-matt',
  'asian-paints-woodtech-melamyne',
  'berger-silk-glamor-dazzle',
  'berger-silk-glamor-high-sheen',
  'berger-silk-glamor-soft-sheen',
  'berger-silk-glamor-matt',
  'berger-silk-metallics',
  'berger-silk-glamart-metallica',
  'berger-silk-glamart-metallica-for-designs',
  'berger-silk-glamart-non-metallic',
  'berger-silk-glamart-vintage',
  'berger-silk-glamart-stucco',
  'berger-silk-glamart-stones-tones',
  'berger-easy-clean',
  'ultratech-grey-cement-ordinary-portland-cement',
  'ultratech-grey-cement-portland-pozzolana-cement',
  'ultratech-grey-cement-portland-pozzolana-super',
  'ultratech-grey-cement-composite-cement',
  'ultratech-grey-cement-weather-plus',
  'ultratech-grey-cement-portland-slag-cement',
  'ultratech-birla-white-cement',
  'ultratech-birla-white-wall-care-putty',
  'ultratech-weather-pro-waterproofing-system',
  'ultratech-tilefixo-sumo-ct',
  'ultratech-tilefixo-nt',
  'ultratech-tilefixo-yt',
  'ultratech-readiplast',
  'ultratech-super-stucco',
  'astral-pex-a-pro',
  'astral-multipex',
  'astral-aquarius',
  'astral-eco-pro',
  'astral-chem-flow',
  'astral-silencio',
  'astral-drain-pro',
  'polycab-green-wire',
  'polycab-suprema-with-e-beam-technology',
  'polycab-optima',
  'polycab-primma',
  'polycab-hr-fr-lsh-lf-green-wire',
  'ultratech-super',
  'ambuja-kawach',
  'jk-super-cement',
  'shree-cement-roofon',
  'astral-cpvc-pro',
  'supreme-swr-pipes',
  'finolex-upvc-pipes',
  'zoloto-brass-valves',
  'polycab-fr-wires',
  'havells-lifeline-plus',
  'finolex-flame-retardant',
  'tata-tiscon-550d',
  'asian-paints-apex-ultima',
  'birla-opus-paints',
  'jk-wallmaxx-putty',
  'jaquar-florentine-diverter',
  'cera-rimless-ewc',
  'myk-laticrete-adhesive',
  'asian-paints-tractor-emulsion',
  'polycab-etira-fr-wire',
  'supreme-cpvc-quote-sample',
  'supreme-agricultural-solvent-sample'
)
OR (
  "description" = 'Ask the team to confirm the exact variant, pack size, colour or grade, price and current availability for your requirement.'
  AND "price" IS NULL
  AND "image" IS NULL
  AND "priceNote" IS NULL
  AND "offerLabel" IS NULL
  AND "minOrderQty" IS NULL
  AND "isInStock" = FALSE
  AND "features" = '{}'::text[]
  AND "applications" = '{}'::text[]
  AND "specifications" = '{}'::jsonb
  AND "galleryImages" = '{}'::text[]
  AND NOT EXISTS (
    SELECT 1 FROM "catalog_listing_variants" v
    WHERE v."listingId" = "catalog_listings"."id"
  )
);
