-- Add further discoverable reference examples using official manufacturer product families.
-- None represent client-approved stock. Every record is quote/availability checked.
INSERT INTO "catalog_listings" (
  "id", "slug", "code", "name", "brand", "brandTagline", "category",
  "categoryLabel", "image", "unit", "packaging", "grade", "description", "priceNote",
  "isInStock", "availabilityStatus", "isPublished", "features", "applications",
  "specifications", "sortOrder", "updatedAt"
) VALUES
('ref-polycab-maxima-green', 'polycab-maxima-plus-green-wire-25sqmm-90m-reference', 'REF-POLYCAB-MAXIMA-GREEN-25-90', 'Polycab MAXIMA+ Green Wire, 2.5 sq mm, 90 m', 'Polycab Wires', 'HR FR-LSH LF House Wires', 'wires', 'Wires & Cables', 'https://cms.polycab.com/media/bpwfax3q/ldis09cyuayl001c25sb025s_img_01.png?format=webp', 'coil', '90 m coil', '2.5 sq mm, single core', 'Online reference example based on the manufacturer’s product page. Confirm the client’s exact make, conductor, colour, coil length, current price, stock and delivery before ordering.', 'Official manufacturer MRP reference observed 06 Oct 2026; confirm local selling price, taxes & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['HR FR-LSH LF insulation', 'Green conductor colour option', 'Manufacturer page lists 2.5 sq mm and 90 m'], ARRAY['Electrical wiring; confirm selection with the project electrician'], '{"Conductor":"Copper","Cross section":"2.5 sq mm","Core":"Single core","Colour":"Green","Length":"90 m","Reference price source":"https://polycab.com/polycabmaximaplus-green-wire-25-sq-mm-90-meters-green/c-5017/p-54619","Reference image source":"https://cms.polycab.com/media/bpwfax3q/ldis09cyuayl001c25sb025s_img_01.png?format=webp","Reference note":"Manufacturer MRP ₹8,350 including taxes on the page checked 06 Oct 2026; confirm current price and client inventory."}', 17, CURRENT_TIMESTAMP),
('ref-ultratech-wp200', 'ultratech-wp-plus-200-waterproofing-liquid-reference', 'REF-ULTRATECH-WP200', 'UltraTech WP+200 Integral Waterproofing Liquid', 'UltraTech Cement', 'Building Product Range', 'paints', 'Paints & Waterproofing', NULL, 'bottle', 'Pack size to be confirmed', 'Integral waterproofing admixture', 'Online reference example of an integral waterproofing liquid mixed with cement for concrete, plaster and mortar. Request a quotation and confirm pack size, application suitability, stock and delivery.', 'Reference listing • request current product price and confirm pack availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Integral waterproofing liquid mixed with cement'], ARRAY['Concrete', 'Plaster', 'Mortar'], '{"Product family":"WP+200","Reference product source":"https://www.ultratechcement.com/for-homebuilders/products/overview-building-product/waterproofing-chemicals","Reference note":"Exact pack and local price were not assumed."}', 18, CURRENT_TIMESTAMP),
('ref-ultratech-bitupro', 'ultratech-bitupro-foundation-waterproofing-reference', 'REF-ULTRATECH-BITUPRO', 'UltraTech BituPro Foundation Damp-proofing Emulsion', 'UltraTech Cement', 'Building Product Range', 'paints', 'Paints & Waterproofing', NULL, 'container', 'Pack size to be confirmed', 'Water-based bitumen emulsion', 'Online reference example of a water-based bitumen emulsion used as a damp-proof coat on foundations. Confirm the substrate, application guidance, pack size, client price and availability before ordering.', 'Reference listing • request current product price and confirm availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Water-based bitumen emulsion', 'Foundation damp-proof coating'], ARRAY['Foundation waterproofing'], '{"Product family":"BituPro","Reference product source":"https://www.ultratechcement.com/for-homebuilders/products/overview-building-product/waterproofing-chemicals","Reference note":"Pack size and current local price not stated in this reference listing."}', 19, CURRENT_TIMESTAMP),
('ref-asian-smartcare-hydroloc', 'asian-paints-smartcare-hydroloc-xtreme-reference', 'REF-ASIAN-SMARTCARE-HYDROLOC', 'Asian Paints SmartCare Hydroloc Xtreme Waterproofing', 'Asian Paints', 'SmartCare Waterproofing', 'paints', 'Paints & Waterproofing', NULL, 'container', 'Pack size to be confirmed', 'Waterproofing product', 'Online reference example from the Asian Paints SmartCare range. Check the application area, substrate, pack size and current product data sheet; price, stock and delivery require confirmation.', 'Reference listing • request current product price, pack & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Waterproofing product family', 'Application and coverage must be checked against the current data sheet'], ARRAY['Waterproofing; application area to be confirmed'], '{"Product family":"SmartCare Hydroloc Xtreme","Reference product source":"https://www.asianpaints.com/waterproofing-products/interiors.html","Reference note":"Pack size and product-specific current rate were not assumed."}', 20, CURRENT_TIMESTAMP),
('ref-jaquar-fusion-prime-mixer', 'jaquar-fusion-prime-extended-basin-mixer-reference', 'REF-JAQUAR-FUS-CHR-29023B', 'Jaquar Fusion Prime Single Lever Extended Basin Mixer, Chrome', 'Jaquar Bath + Light', 'Fusion Prime', 'sanitary', 'Sanitaryware & Bath Fittings', NULL, 'piece', 'One mixer', 'Model FUS-CHR-29023B', 'Online reference example using an exact manufacturer model code. Confirm installation type, finish, included parts, current client price, stock and delivery before ordering.', 'Reference listing • request current model price and confirm finish & availability', false, 'CHECK_AVAILABILITY', true, ARRAY['Single lever basin mixer', 'Chrome model code FUS-CHR-29023B'], ARRAY['Washbasin installation; check fitting requirements'], '{"Model":"FUS-CHR-29023B","Finish":"Chrome","Reference product source":"https://www.jaquar.com/en/faucets-2","Reference note":"Manufacturer model identification; no price assumed."}', 21, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name", "brand" = EXCLUDED."brand", "brandTagline" = EXCLUDED."brandTagline",
  "category" = EXCLUDED."category", "categoryLabel" = EXCLUDED."categoryLabel", "image" = EXCLUDED."image", "unit" = EXCLUDED."unit",
  "packaging" = EXCLUDED."packaging", "grade" = EXCLUDED."grade", "description" = EXCLUDED."description",
  "priceNote" = EXCLUDED."priceNote", "isInStock" = EXCLUDED."isInStock",
  "availabilityStatus" = EXCLUDED."availabilityStatus", "isPublished" = EXCLUDED."isPublished",
  "features" = EXCLUDED."features", "applications" = EXCLUDED."applications",
  "specifications" = EXCLUDED."specifications", "sortOrder" = EXCLUDED."sortOrder", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "catalog_listing_variants" (
  "id", "listingId", "code", "label", "attributes", "unit", "price",
  "compareAtPrice", "priceNote", "isInStock", "availabilityStatus", "sortOrder", "updatedAt"
)
SELECT 'refv-polycab-maxima-green-25-90', l."id", 'REFV-POLYCAB-MAXIMA-GREEN-25-90',
  'Green · 2.5 sq mm · 90 m',
  '{"Colour":"Green","Cross section":"2.5 sq mm","Core":"Single core","Length":"90 m"}'::jsonb,
  'coil', 8350.00::numeric, NULL::numeric,
  'Manufacturer MRP reference observed 06 Oct 2026; confirm local selling price and availability.',
  false, 'CHECK_AVAILABILITY', 0, CURRENT_TIMESTAMP
FROM "catalog_listings" l WHERE l."slug" = 'polycab-maxima-plus-green-wire-25sqmm-90m-reference'
ON CONFLICT ("code") DO NOTHING;
