-- Editorial resources and service-desk directory entries for the public preview.
-- These are informational pages, not promises of specific delivery or paid expert services.
INSERT INTO "blog_posts" ("id", "title", "slug", "summary", "body", "featuredImageUrl", "status", "publishedAt", "authorName", "createdAt", "updatedAt") VALUES
('journal-ncr-material-plan', 'How to plan a construction material list for a Delhi NCR project', 'construction-material-list-delhi-ncr', 'A practical sequence for preparing a material list, checking specifications and requesting a location-specific quote in Noida, Delhi, Gurugram, Ghaziabad, Faridabad and nearby areas.', 'Start with the project stage and a drawing, bill of quantities or contractor list. Group requirements into cement and steel, plumbing, electrical, paint and finishing materials so that quantities and delivery stages are easier to review.\n\nWrite down the make, grade, size, unit and pack wherever known. A request such as “2.5 sq mm copper wire, single core, red, 90 m coil” is easier to verify than a brand name alone. For paints and adhesives, include the surface, finish, pack size and shade or colour requirement.\n\nBefore confirming a purchase, compare the requested specification with the quote, check tax treatment and ask whether partial delivery is possible. Material Square serves Delhi NCR enquiries; product availability, delivery timing and coverage are confirmed for the project PIN code.', '/images/materials-editorial.png', 'PUBLISHED', CURRENT_TIMESTAMP, 'Material Square Editorial Desk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('journal-cement-grade', 'PPC or OPC cement: what to check before you order', 'ppc-or-opc-cement-project-guide', 'Understand the common cement grade labels, 50 kg bag units and the project details to confirm before requesting a cement quote in Delhi NCR.', 'PPC and OPC describe different cement types; the appropriate choice depends on the design, application, engineer’s direction and applicable standards. Do not choose a grade from a product title alone. Check the approved specification or ask the site engineer.\n\nWhen requesting a quote, include the brand, grade, bag size, estimated quantity, delivery location and required date. Ask the seller to confirm the manufacturing and delivery details for the actual lot. Keep bags dry, raised from the floor and protected from moisture after delivery.\n\nFor projects in Noida, Greater Noida, Delhi, Gurugram, Ghaziabad or Faridabad, request a location-specific quote and confirm stock and delivery separately. Online reference listings are examples only; they are not a live stock statement or client-approved selling price.', '/images/materials-editorial.png', 'PUBLISHED', CURRENT_TIMESTAMP, 'Material Square Editorial Desk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('journal-waterproofing', 'Waterproofing materials: diagnose the source before choosing a coating', 'waterproofing-materials-damp-wall-guide', 'A simple checklist for damp patches, cracks, terraces and bathrooms, with questions to take to a qualified applicator or product specialist.', 'A damp patch can come from plumbing leakage, rainwater entry, a terrace, a crack or moisture moving through a wall. A decorative top coat alone may not solve the source. Identify where and when the moisture appears, and document the area with clear photographs.\n\nAsk a qualified professional to inspect the affected surface and recommend a system for that substrate and exposure. Product families can include crack fillers, primers, cementitious coatings, membranes and protective top coats; they are not interchangeable. Follow the product data sheet for preparation, coverage, coats and curing.\n\nMaterial Square can help customers in Delhi NCR request product information and a quote for listed waterproofing materials. Inspection, application services, stock and delivery are subject to separate confirmation.', '/images/materials-editorial.png', 'PUBLISHED', CURRENT_TIMESTAMP, 'Material Square Editorial Desk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('journal-wire-spec', 'Choosing house wire: match the circuit, conductor and installation', 'house-wire-size-colour-and-length-checklist', 'Use a specification checklist for wire size, copper conductor, insulation class, colour and coil length before adding wire to a project material list.', 'Wire selection should follow the electrical design and local requirements. Ask the electrician to specify the conductor material and cross-section, insulation type, colour convention, coil length and quantity for each circuit. Do not select a cable size from an appliance example alone.\n\nA product title can contain many attributes: for example, a single-core copper house wire with a stated cross-section, insulation class, colour and coil length. Confirm that all of those fields match the approved requirement and that the chosen brand’s product documentation applies to that exact combination.\n\nFor a Delhi NCR quote, share the full specification, brand preference, quantity and site PIN code. Colour and size options shown in an online reference catalogue are subject to current inventory confirmation.', '/images/materials-editorial.png', 'PUBLISHED', CURRENT_TIMESTAMP, 'Material Square Editorial Desk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('journal-pipe-material', 'CPVC, uPVC and pipe fittings: build a clear plumbing specification', 'cpvc-upvc-pipes-and-fittings-checklist', 'The pipe material, diameter, pressure class, SDR and fitting compatibility all matter when specifying plumbing materials for a home or commercial site.', 'Start with the service: hot or cold water, drainage, rainwater or another application. The plumbing design and product manufacturer’s recommendations determine which pipe system is appropriate. Then list the material, nominal diameter, pressure class or SDR, length and compatible fittings.\n\nFor valves, add the nominal bore, body material, connection type and pressure rating. A matching diameter by itself does not guarantee compatibility. Keep the final bill of materials aligned to the drawings and the installer’s specification.\n\nMaterial Square accepts pipe and fitting enquiries for Delhi NCR projects. Confirm the precise model, available lengths, quantity, taxes, delivery location and timing on the quote.', '/images/materials-editorial.png', 'PUBLISHED', CURRENT_TIMESTAMP, 'Material Square Editorial Desk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('journal-paint-shade-pack', 'Paint pack sizes and colour shades: what to confirm before ordering', 'paint-pack-size-colour-and-finish-guide', 'A helpful paint checklist covering surface, interior or exterior use, finish, shade, base, pack size and tinting before you request a quote.', 'A paint choice depends on the surface and its condition, interior or exterior exposure, finish, shade and compatible primer. If a colour is being tinted, record the shade code and product base. A colour name alone may not uniquely identify the result.\n\nPack sizes affect the quantity and price. Estimate coverage using the manufacturer’s guidance and the site conditions; porosity, preparation and number of coats change consumption. Keep some batch continuity in mind for large areas and check that the supplied shade and finish match the approved sample.\n\nAsk for the specific brand, product family, finish, shade or base, pack size and quantity. Reference prices can change with the pack and tinting. For Noida, Delhi, Gurugram, Ghaziabad and Faridabad projects, delivery and local availability are confirmed with the quote.', '/images/materials-editorial.png', 'PUBLISHED', CURRENT_TIMESTAMP, 'Material Square Editorial Desk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('journal-tile-adhesive', 'Tile adhesive selection: match the adhesive to the tile and substrate', 'tile-adhesive-selection-guide', 'Before ordering tile adhesive, confirm tile material and format, substrate, indoor or outdoor exposure, wet-area needs and the manufacturer’s application guidance.', 'Tile size and material, substrate condition, exposure to water and whether the work is indoors or outdoors affect adhesive selection. Check the product data sheet for the recommended use, mixing, open time, coverage and curing instructions.\n\nAsk the installer to confirm the adhesive class or product family and expected consumption. Also record pack weight and colour where grout or visible joints are part of the same scope. Adhesive cannot correct an unsuitable or poorly prepared substrate.\n\nFor a quote, provide tile and substrate details, quantity, brand preference and site PIN code. Material Square can check listed options for Delhi NCR enquiries, subject to confirmation of stock and delivery.', '/images/materials-editorial.png', 'PUBLISHED', CURRENT_TIMESTAMP, 'Material Square Editorial Desk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('journal-delivery-planning', 'Coordinating construction material deliveries across Delhi NCR', 'construction-material-delivery-planning-delhi-ncr', 'Plan material drops around site access, unloading, storage and work stages for projects in Delhi, Noida, Gurugram, Ghaziabad, Faridabad and Greater Noida.', 'Before a delivery is scheduled, share the full site address and PIN code, site contact, access restrictions, unloading arrangements and preferred time window. Check whether a vehicle can reach the unloading point and whether the site has safe, dry storage.\n\nPlan materials by work stage. Cement and steel storage needs differ from paint, wire coils, pipe lengths and sanitary products. A staged delivery can reduce congestion, but minimum quantities, vehicle capacity and availability may affect the plan.\n\nMaterial Square handles enquiries across its stated Delhi NCR service area. A city name does not guarantee service at every address: the team confirms PIN code coverage, inventory, transport, charges and timing before accepting an order.', '/images/materials-editorial.png', 'PUBLISHED', CURRENT_TIMESTAMP, 'Material Square Editorial Desk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO UPDATE SET
  "title" = EXCLUDED."title", "summary" = EXCLUDED."summary", "body" = EXCLUDED."body",
  "featuredImageUrl" = EXCLUDED."featuredImageUrl", "status" = EXCLUDED."status",
  "publishedAt" = EXCLUDED."publishedAt", "authorName" = EXCLUDED."authorName", "updatedAt" = CURRENT_TIMESTAMP;

-- These are staffed Material Square product-advice desks, not fictitious named individuals.
INSERT INTO "expert_advisors" ("id", "name", "serviceType", "expertise", "city", "servicePincodes", "description", "imageUrl", "isPublished", "createdAt", "updatedAt") VALUES
('desk-cement-steel', 'Cement & Steel Product Desk', 'Product selection', 'Cement grades, TMT specifications, quantities and quote preparation', 'Delhi NCR', ARRAY[]::text[], 'Share the approved grade, diameter, quantity and site PIN code. Our team can help route a product enquiry; technical design, stock and delivery details are confirmed separately.', NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('desk-paint-waterproofing', 'Paint & Waterproofing Product Desk', 'Product selection', 'Paint finish and pack options, shade details, waterproofing product enquiries', 'Delhi NCR', ARRAY[]::text[], 'Tell us the surface, exposure, product family, pack size and shade or base. Application advice and on-site inspection are not implied; we will confirm what support is available for your location.', NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('desk-electrical', 'Electrical Materials Product Desk', 'Product selection', 'House wire attributes, colour, coil length and electrical material enquiries', 'Delhi NCR', ARRAY[]::text[], 'Share the electrician-approved cable specification, colour, brand preference and quantity. We help with product enquiries; circuit design and installation must be confirmed with a qualified electrician.', NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('desk-plumbing', 'Pipes & Plumbing Product Desk', 'Product selection', 'Pipe material, nominal diameter, pressure class, fittings and valve enquiries', 'Delhi NCR', ARRAY[]::text[], 'Send the plumbing specification and site PIN code so the team can check listed products and prepare an enquiry. Compatibility, current price, stock and delivery are confirmed before purchase.', NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('desk-finishes', 'Sanitary & Tile-fixing Product Desk', 'Product selection', 'Sanitaryware, faucets, tile adhesive and finishing material enquiries', 'Delhi NCR', ARRAY[]::text[], 'Share the product type, model or finish, required quantity and project location. We can help identify catalogue options; model compatibility, quote and delivery remain subject to confirmation.', NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name", "serviceType" = EXCLUDED."serviceType", "expertise" = EXCLUDED."expertise",
  "city" = EXCLUDED."city", "servicePincodes" = EXCLUDED."servicePincodes", "description" = EXCLUDED."description",
  "imageUrl" = EXCLUDED."imageUrl", "isPublished" = EXCLUDED."isPublished", "updatedAt" = CURRENT_TIMESTAMP;
